class MyCustomError(Exception):
    pass

raise MyCustomError("That was not planned")

